// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnPAXReNivoFV2Yvtl9rk_GD9X_rzRUVU',
    appId: '1:845627304143:web:dc27638a36e27d0fa82fba',
    messagingSenderId: '845627304143',
    projectId: 'weather-forecast-c1c3c',
    authDomain: 'weather-forecast-c1c3c.firebaseapp.com',
    storageBucket: 'weather-forecast-c1c3c.firebasestorage.app',
    measurementId: 'G-B5X4MHP22Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAksczMw1PeMhFP0GDh70slGSOlvbNugPc',
    appId: '1:845627304143:android:55053b88ec1dd873a82fba',
    messagingSenderId: '845627304143',
    projectId: 'weather-forecast-c1c3c',
    storageBucket: 'weather-forecast-c1c3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYBlOTHHCKGlPOQApwZz_mUI7LreAisOs',
    appId: '1:845627304143:ios:2a599af04f0baab0a82fba',
    messagingSenderId: '845627304143',
    projectId: 'weather-forecast-c1c3c',
    storageBucket: 'weather-forecast-c1c3c.firebasestorage.app',
    iosBundleId: 'com.example.weatherForecast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYBlOTHHCKGlPOQApwZz_mUI7LreAisOs',
    appId: '1:845627304143:ios:2a599af04f0baab0a82fba',
    messagingSenderId: '845627304143',
    projectId: 'weather-forecast-c1c3c',
    storageBucket: 'weather-forecast-c1c3c.firebasestorage.app',
    iosBundleId: 'com.example.weatherForecast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnPAXReNivoFV2Yvtl9rk_GD9X_rzRUVU',
    appId: '1:845627304143:web:30980b9d80018333a82fba',
    messagingSenderId: '845627304143',
    projectId: 'weather-forecast-c1c3c',
    authDomain: 'weather-forecast-c1c3c.firebaseapp.com',
    storageBucket: 'weather-forecast-c1c3c.firebasestorage.app',
    measurementId: 'G-73ETXH34MH',
  );
}
